#!/bin/bash

# make sure we HAVE! node modules
if ! [ -e 'node_modules/.package-lock.json' ]; then
    echo "Installing Node Stuff"
    npm i;

    # remove unneccesary files
    rm -f package.json
    rm -f package-lock.json
    rm -f readme.txt
fi

$(which node || which nodejs) app
# FIX idk what to fix works phenomenally